src/Entity/CvEducation.php
<?php

namespace App\Entity;

use App\Repository\CvEducationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CvEducationRepository::class)]
class CvEducation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $institution = null;

    #[ORM\Column(length: 255)]
    private ?string $faculty = null;

    #[ORM\Column(length: 255)]
    private ?string $study_field = null;

    #[ORM\Column(length: 255)]
    private ?string $education_level = null;

    #[ORM\Column]
    private ?bool $status = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\ManyToOne(inversedBy: 'educations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?CvBaseInfo $cv = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInstitution(): ?string
    {
        return $this->institution;
    }

    public function setInstitution(string $institution): self
    {
        $this->institution = $institution;

        return $this;
    }

    public function getFaculty(): ?string
    {
        return $this->faculty;
    }

    public function setFaculty(string $faculty): self
    {
        $this->faculty = $faculty;

        return $this;
    }

    public function getStudyField(): ?string
    {
        return $this->study_field;
    }

    public function setStudyField(string $study_field): self
    {
        $this->study_field = $study_field;

        return $this;
    }

    public function getEducationLevel(): ?string
    {
        return $this->education_level;
    }

    public function setEducationLevel(string $education_level): self
    {
        $this->education_level = $education_level;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getCv(): ?CvBaseInfo
    {
        return $this->cv;
    }

    public function setCv(?CvBaseInfo $cv): self
    {
        $this->cv = $cv;

        return $this;
    }
}

src/Entity/CvJobExperience.php
<?php

namespace App\Entity;

use App\Repository\CvJobExperienceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CvJobExperienceRepository::class)]
class CvJobExperience
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $company = null;

    #[ORM\Column(length: 255)]
    private ?string $job_title = null;

    #[ORM\Column]
    private ?bool $work_load = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\ManyToOne(inversedBy: 'experiences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?CvBaseInfo $cv = null;

    #[ORM\OneToMany(mappedBy: 'job', targetEntity: CvJobExperienceSkills::class, orphanRemoval: true)]
    private Collection $skills;

    public function __construct()
    {
        $this->skills = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->job_title;
    }

    public function setJobTitle(string $job_title): self
    {
        $this->job_title = $job_title;

        return $this;
    }

    public function isWorkLoad(): ?bool
    {
        return $this->work_load;
    }

    public function setWorkLoad(bool $work_load): self
    {
        $this->work_load = $work_load;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getCv(): ?CvBaseInfo
    {
        return $this->cv;
    }

    public function setCv(?CvBaseInfo $cv): self
    {
        $this->cv = $cv;

        return $this;
    }

    /**
     * @return Collection<int, CvJobExperienceSkills>
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(CvJobExperienceSkills $skill): self
    {
        if (!$this->skills->contains($skill)) {
            $this->skills->add($skill);
            $skill->setJob($this);
        }

        return $this;
    }

    public function removeSkill(CvJobExperienceSkills $skill): self
    {
        if ($this->skills->removeElement($skill)) {
            // set the owning side to null (unless already changed)
            if ($skill->getJob() === $this) {
                $skill->setJob(null);
            }
        }

        return $this;
    }
}

src/Entity/CvPicture.php
<?php

namespace App\Entity;

use App\Repository\CvPictureRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CvPictureRepository::class)]
class CvPicture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $file_name = null;

    #[ORM\ManyToOne(inversedBy: 'pictures')]
    #[ORM\JoinColumn(nullable: false)]
    private ?CvBaseInfo $cv = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getCv(): ?CvBaseInfo
    {
        return $this->cv;
    }

    public function setCv(?CvBaseInfo $cv): self
    {
        $this->cv = $cv;

        return $this;
    }
}

src/Controller/ViewCvController.php
<?php

namespace App\Controller;

use App\Repository\CvBaseInfoRepository;
use App\Repository\CvJobExperienceRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;

class ViewCvController extends AbstractController
{
    private CvBaseInfoRepository $cvBaseInfoRepository;
    private CvJobExperienceRepository $cvJobExperienceRepository;

    public function __construct(CvBaseInfoRepository $cvBaseInfoRepository, CvJobExperienceRepository $cvJobExperienceRepository) {

        $this->cvBaseInfoRepository = $cvBaseInfoRepository;
        $this->cvJobExperienceRepository = $cvJobExperienceRepository;
    }

    #[Route('/view-cv', name: 'app_view_cv')]
    public function index(ManagerRegistry $registry): Response
    {
        $session = new Session();
        $cv = $session->get("CvId");

        if ($cv == null) {
            return $this->redirectToRoute('app_cv_list');
        }

        $baseInfo = $this->cvBaseInfoRepository->find($cv);
        $address = $baseInfo->getAddresses()->first();
        $education = $baseInfo->getEducations()->getValues();

        $workExperience = $this->cvJobExperienceRepository->findBy(["cv" => $cv]);
        $workExperienceSkills = [];
        foreach ($workExperience as $experience){
            $workExperienceSkills[] = $experience->getSkills()->getValues();
        }
        $languages = $baseInfo->getLanguages()->getValues();
        $references = $baseInfo->getCvReferences()->getValues();
        $webLinks = $baseInfo->getUrls()->getValues();
        $picture = $baseInfo->getPictures()->first();

        return $this->render('view_cv/index.html.twig', [
            'base_info' => $baseInfo,
            'address' => $address,
            'educations' => $education,
            'work_experiences' => $workExperience,
            'work_experience_skills' => $workExperienceSkills,
            'languages' => $languages,
            'references' => $references,
            'web_links' => $webLinks,
            'picture' => $picture
        ]);
    }
}

templates/view_cv/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ViewCvController!{% endblock %}

{% block body %}
    <div class="print:hidden flex justify-center items-center h-fit w-full">
        <div class="flex justify-center items-center h-16 w-fit">
            <button class="background-black-steel color-gold-leaf px-4 py-2 rounded transition duration-500 hover:scale-105"
                    onclick="window.print()">Print Cv
            </button>
        </div>
    </div>

    <main class="font-firago hyphens-manual">
        <div class="p-6 mx-auto page max-w-2xl print:max-w-letter md:max-w-letter md:h-letter xsm:p-8 sm:p-9 md:p-16 bg-white">
            <header class="mb-8 md:mb-11 w-full color-gold-leaf">
                <div class="relative w-full">
                    {% if picture is defined %}
                        {% if picture != null %}
                            <img class="absolute right-0 top-0 w-20 h-30"
                                 src="{{ asset('pictures/' ~ picture.fileName ) }}"
                                 alt="{{ picture.fileName }}">
                        {% endif %}
                    {% endif %}
                    {% if base_info is defined %}
                    {% if base_info != null %}
                    <h1 class="text-2xl color-silver font-bold"> {{ base_info.name }} {{ base_info.surname }} </h1>
                    <p> Email: {{ base_info.email }}</p>
                    <p> Phone: {{ base_info.phone }}</p>
                </div>
            </header>
            <div class="md:col-count-2 print:col-count-2 col-gap-md md:h-letter-col print:h-letter-col col-fill-auto">
                <section class="mt-8 first:mt-0">
                    <div class="break-inside-avoid">
                        <section class="mb-4.5 break-inside-avoid">
                            <header>
                                <h3 class="text-lg font-semibold text-gray-700 leading-snugish">
                                    About Me
                                </h3>
                            </header>
                            <p class="mt-2.1 text-sm text-gray-700 leading-normal">
                                {{ base_info.about }}
                            </p>
                        </section>
                    </div>
                </section>
                {% endif %}
                {% endif %}
                {% if base_info is defined %}
                {% if base_info != null %}
                <section class="mt-8 first:mt-0">
                    <div class="break-inside-avoid">
                        <section class="mb-4.5 break-inside-avoid">
                            <header>
                                <h3 class="text-lg font-semibold text-gray-700 leading-snugish">
                                    Education
                                </h3>
                            </header>

                            {% for education in educations %}
                                <p class="leading-normal text-sm text-gray-650">
                                    ({{ education.startDate|date('d/m/Y') }} - {{ education.endDate|date('d/m/Y') }})
                                </p>
                                <p class="mt-2.1 text-sm text-gray-700 leading-normal">
                                    {{ education.institution }} - {{ education.faculty }} - {{ education.studyField }}
                                    ({{ education.educationLevel }} -
                                    {% if education.status == true %}
                                    Finished
                                {% else %}
                                    Unfinished
                                    {% endif %})
                                </p>
                            {% endfor %}
                        </section>

                    </div>
                </section>
                {% endif %}
                {% endif %}
                {% if work_experiences is defined %}
                    {% if work_experiences != null %}
                        <section class="mb-4.5 break-inside-avoid">
                            <header>
                                <h3 class="text-lg font-semibold text-gray-700 leading-snugish">
                                    Work Experience
                                </h3>
                                {% for work_experience in work_experiences %}
                                <p class="leading-normal text-md text-gray-650">
                                    {{ work_experience.company }} - {{ work_experience.jobTitle }}
                                </p>
                                <p class="leading-normal text-sm text-gray-650">
                                    ({{ work_experience.startDate|date('d/m/Y') }}
                                    - {{ work_experience.endDate|date('d/m/Y') }})
                                </p>
                            </header>
                            <ul>
                                {% if work_experience_skills is defined %}
                                    {% if work_experience_skills != null %}
                                        {% for skills in work_experience_skills %}
                                            {% for skill in skills %}
                                                {% if skill.job.id == work_experience.id %}
                                                    <li class="mt-2.1 text-sm text-gray-700 leading-normal">
                                                        <span class="absolute -ml-3 sm:-ml-3.2 select-none transform -translate-y-px">-</span>
                                                        {{ skill.skill }} ({{ skill.type }})
                                                    </li>
                                                {% endif %}
                                            {% endfor %}
                                        {% endfor %}
                                    {% endif %}
                                {% endif %}
                            </ul>
                            {% endfor %}
                        </section>
                    {% endif %}
                {% endif %}

                {% if languages is defined %}
                    {% if languages != null %}
                        <section class="mt-8 first:mt-0">
                            <div class="break-inside-avoid">
                                <section class="mb-4.5 break-inside-avoid">
                                    <header>
                                        <h3 class="text-lg font-semibold text-gray-700 leading-snugish">
                                            Languages
                                        </h3>
                                    </header>
                                    <ul>
                                        {% for language in languages %}
                                            <li class="mt-2.1 text-sm text-gray-700 leading-normal">
                                                <span class="absolute -ml-3 sm:-ml-3.2 select-none transform -translate-y-px">-</span>
                                                {{ language.language }}
                                                {% if language.level == 1 %}
                                                    (Elementary Proficiency)
                                                {% elseif language.level == 2 %}
                                                    (Limited Working Proficiency)
                                                {% elseif language.level == 3 %}
                                                    (Professional Working Proficiency)
                                                {% elseif language.level == 4 %}
                                                    (Full Professional Proficiency)
                                                {% elseif language.level == 5 %}
                                                    (Native / Bilingual Proficiency)
                                                {% endif %}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </section>
                            </div>
                        </section>
                    {% endif %}
                {% endif %}

                {% if references is defined %}
                    {% if references != null %}
                        <section class="mt-8 first:mt-0">
                            <div class="break-inside-avoid">
                                <section class="mb-4.5 break-inside-avoid">
                                    <header>
                                        <h3 class="text-lg font-semibold text-gray-700 leading-snugish">
                                            References
                                        </h3>
                                    </header>
                                    <ul>
                                        {% for reference in references %}
                                            <li class="mt-2.1 text-sm text-gray-700 leading-normal">
                                                <span class="absolute -ml-3 sm:-ml-3.2 select-none transform -translate-y-px">-</span>
                                                {{ reference.name }} ({{ reference.contact }})
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </section>
                            </div>
                        </section>
                    {% endif %}
                {% endif %}

                {% if web_links is defined %}
                    {% if web_links != null %}
                        <section class="mt-8 first:mt-0">
                            <div class="break-inside-avoid">
                                <section class="mb-4.5 break-inside-avoid">
                                    <header>
                                        <h3 class="text-lg font-semibold text-gray-700 leading-snugish">
                                            Web Sites
                                        </h3>
                                    </header>
                                    <ul>
                                        {% for link in web_links %}
                                            <li class="mt-2.1 text-sm text-gray-700 leading-normal">
                                                <span class="absolute -ml-3 sm:-ml-3.2 select-none transform -translate-y-px">-</span>
                                                {{ link.url }}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </section>
                            </div>
                        </section>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </main>

{% endblock %}